### PR TITLE
Move to .net Core 2.0

### PR DESCRIPTION
**Pull request by JonyTek**
As the title suggests I have moved the repo to use .net Core 2.0.

This is a requirement for a project I am working on.

I did also refactor some namespaces which will be breaking changes for anyone using this project so I will understand if you reject this PR.

I have packaged up the build and it is now hosted in nuget for ease of use for anyone interested. https://www.nuget.org/packages/Zoopla.Net.Core/1.0.0

I wrote a couple of integration tests which I have used to update the readme file so that people can get up and running quickly, not that it's difficult but I always like to see a quick usagae example.

### CODE REVIEW

**Comment by itsthatianguy** [comment]
Thanks for the Pull Request!

I do have a couple of reservations about merging it in however.
As you mentioned, there would be breaking changes to existing users, which I'm keen to avoid.
The other issue is that I don't understand the need for the change you've made to move the library from netstandard to netcoreapp. The library is currently written to target .NET Standard 1.6, which is supported by both .NET Core 1.0 and 2.0, so no change is required to make this compatible with .NET Core 2.0.
The change will actually limit it more I think, as I don't think the changes would be compatible with .NET Core 1.0.

Obviously if I've misunderstood anything feel free to correct me 😄

**Comment by JonyTek** [comment]
No problem. It was my understanding that standard 1.6 was only compatible with core version 1.0, I must be mistaken.

Thanks.

Closed.

**Comment by clockworkmice** [comment]
You're quite right @ianrufus

This reminds me actually. Did you publish your budget package to include the disambiguation PR I did a while back? That'd be awesome 😀

**Comment by itsthatianguy** [comment]
@clockworkmice It looks like I didn't. I'll get a new one published this week, thanks for the reminder! 👍

**Comment by itsthatianguy** [comment]
@clockworkmice Published the update with your change in, version 1.2.1
Added you as an author on the package as well, hope you don't mind! 👍

**Pull request closed without merging**
